bt_topic_trigger: 
  plugins: ["trajectory_loader_plugin","move_to_plugin","move_to_conf_plugin","wait_plugin","robotiq_2f85_plugin"] 
  trees_paths: ["/home/holden/projects/holden_ws/src/holden_demo/trees/test_bt_topic_trigger_fancy"]
  priority_trees: ["s"] 
  bt_topic: "/gesture_recognition"

