bt_executer:

  wait:
    wait_ms: 100 #ms

  open_gripper:
    position: 0.07
    max_effort: 0.1 
  
  close_gripper:
    position: 0.0
    max_effort: 0.0

  add_bottle:
    frame_id: "world"
    object_id: "bottle"
    primitive_type: "cylinder"
    dimensions:
      height: 0.12
      radius: 0.02
    pose:
      position:
        x: 1.38
        y: -0.14
        z: 0.12
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    add: true

  remove_bottle:
    object_id: "bottle"
    add: false

  attach_bottle:
    frame_id: "fr3_hand"
    object_id: "bottle"
    touch_links: ["fr3_hand","fr3_hand_tcp", "fr3_leftfinger", "fr3_rightfinger"]
    attach: true

  detach_bottle:
    frame_id: "fr3_hand"
    object_id: "bottle"
    attach: false

  move_to_conf_home:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations: [0.0,-1.5312335574200928,-1.57,1.628033529891,-1.6274872486440086,-1.57,0.0]

  move_to_conf_pick_approach:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations: 
      - 0.19197620106038832
      - 0.11701437911634627
      - 0.46680892648820776
      - -2.099846761107594
      - -0.06557814420012595
      - 2.203800505639704
      - 1.4805658005795939

  move_to_conf_pick:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations: [1.0,-0.4046571890460413,-1.1754615942584437,1.6654682159423828,-2.0698588530169886,-1.5612176100360315,0.0]

  move_to_conf_place_approach:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations:
      - -0.3890962297483688
      - -0.049476036365181754
      - -0.3417838013993172
      - -2.1831496900303717
      - -0.019045340397745365
      - 2.1367188733160454
      - 0.06550199382413471

  move_to_conf_place:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations: 
      - -0.40980642100012316
      - 0.34876069845937385
      - -0.28420102708886946
      - -2.231272917890299
      - 0.1762769992784698
      - 2.5603757166657815
      - -0.03981556460702614

  move_to_conf_give:
    group_name: "fr3_arm"
    fjt_action_name: "/fr3_arm_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
    target_joints_configurations: [0.5351068777131383,-1.5312471850963396,-1.1439016718693455,1.1703671318470665,-2.0943297204583287,-1.5699958782745058,0.0]
