bt_executer:

  wait:
    wait_ms: 100 #ms
    
  wait_long:
    wait_ms: 1500 #ms

  open_gripper:
    position: 0.0 # between 0.0 and 0.7929
    max_effort: 0.1 
  
  close_gripper:
    position: 0.25 # between 0.0 and 0.7929
    max_effort: 0.0

  close_gripper_bottle:
    position: 0.35 # between 0.0 and 0.7929
    max_effort: 0.0

  add_bottle:
    frame_id: "world"
    object_id: "bottle"
    primitive_type: "cylinder"
    dimensions:
      height: 0.15
      radius: 0.02
    pose:
      position:
        x: 1.50
        y: -0.21
        z: 0.13
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    add: true

  remove_bottle:
    object_id: "bottle"
    add: false

  attach_bottle:
    frame_id: "flange"
    object_id: "bottle"
    touch_links: ["robotiq_85_left_finger_link", "robotiq_85_left_finger_tip_link", "robotiq_85_left_inner_knuckle_link", "robotiq_85_left_knuckle_link",
                  "robotiq_85_right_finger_link", "robotiq_85_right_finger_tip_link", "robotiq_85_right_inner_knuckle_link", "robotiq_85_right_knuckle_link"]
    attach: true

  detach_bottle:
    frame_id: "flange"
    object_id: "bottle"
    attach: false

  add_cup:
    frame_id: "world"
    object_id: "cup"
    primitive_type: "cylinder"
    dimensions:
      height: 0.05
      radius: 0.02
    pose:
      position:
        x: 1.38
        y: -0.14
        z: 0.08
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    add: true

  remove_cup:
    object_id: "cup"
    add: false

  attach_cup:
    frame_id: "flange"
    object_id: "cup"
    touch_links: ["robotiq_85_left_finger_link", "robotiq_85_left_finger_tip_link", "robotiq_85_left_inner_knuckle_link", "robotiq_85_left_knuckle_link",
                  "robotiq_85_right_finger_link", "robotiq_85_right_finger_tip_link", "robotiq_85_right_inner_knuckle_link", "robotiq_85_right_knuckle_link"]
    attach: true

  detach_cup:
    frame_id: "flange"
    object_id: "cup"
    attach: false

  move_to_conf_pick_bottle_to_serve:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.0, -2.425441567097799, -0.7728436628924769, 0.8675899505615234, -1.354720417653219, -1.6145175139056605, -0.20663577715028936]


  move_to_conf_serve_water:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [-0.001, -2.365943257008688, -0.9445703665362757, 1.5934805870056152, -3.584280792866842, -1.2271745840655726, -0.059723679219381154]


  move_to_conf_bottle_above_cup:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [-0.001, -2.4266515413867396, -1.10405141512026, 1.2531943321228027,  -2.062650505696432, -1.429532829915182, -0.01507741609682256]


  move_to_conf_place_bottle:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [-0.001, -2.4781976381884974, -0.7120240370379847, 0.7691464424133301, -1.1630542914019983, -1.4505437056170862, 0.005668913014233112]

  move_to_conf_place_bottle:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [9.782193911657977e-05, -2.3759295976863477, -0.9679339501213478, 1.381629271670591, -2.059235457759855, -1.5774652564823715, -0.00038097143495382396]

  move_to_conf_leave_bottle:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [2.177132000216099e-05, -2.3759347404592903, -0.8976791341711223, 1.17047779699086, -1.8831213602615358, -1.5664172929178446, -0.08791978203058662]

  move_to_conf_pick_bottle:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.9998398634706795, -0.44009119020819965, -0.8624521511000034, 1.152699149274079, -1.8479994313672998, -1.5309616309639618, 0.00026360936569981276]

  move_to_conf_home:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.0,-1.5312335574200928,-1.57,1.628033529891,-1.6274872486440086,-1.57,0.0]

  move_to_conf_pick_approach:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [1.0,-0.4049928824054163,-1.31996995607485,1.3111495971679688,-1.6016228834735315,-1.5311372915851038,0.00025166873820126057]

  move_to_conf_pick:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [1.0,-0.40485320109133005,-1.0737033838862093,1.7511705168529188,-2.2350871850604244,-1.5311372915851038,0.00025166873820126057]

  move_to_conf_place_approach:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.0,-2.342357937489645,-1.2317474524127405,1.2642273902893066,-1.6274951140033167,-1.5775168577777308,-0.000287357960836232]

  move_to_conf_place:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.0, -2.27041712745959, -0.9679289117031925, 1.5576909440570432, -2.129502916015714, -1.5775032586727378, -0.00027930167541766193]

  move_to_conf_give:
    group_name: "ur_on_linear_guide"
    fjt_action_name: "/ur_on_linear_guide_scaled_controller/follow_joint_trajectory"
    simulation: False
    speed_scaling_topic: "/ur_on_linear_guide_speed_ovr"
    scaling: 100
    pipeline_id: "ompl"
    planner_id: "BiTRRT"
    velocity_scaling_factor: 0.01
    acceleration_scaling_factor: 0.01
    joints_names: ["guide_linear_joint", "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    target_joints_configurations: [0.5351068777131383,-1.5312471850963396,-1.1439016718693455,1.1703671318470665,-2.0943297204583287,-1.5699958782745058,0.0]
