string_velocity_position_converter_node:
  ros__parameters:
    joint_name: "guide_linear_joint"
    joint_limits: [0.0,1.0]
    velocity_command_topic: "/gesture_recognition"
    position_command_topic: "/linear_guide_position_forward_controller/commands"
    speed_mapping:
      - left
      - "-0.5"
      - "1000000.0" #seconds to reset speed 
      - right
      - "0.5"
      - "1000000.0" #seconds to reset speed
      - down
      - "0"
      - "0.001" #seconds to reset speed
    loop_frequency: 1000.0 #Hz
    velocity_threshold: 0.05

